---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-auth
  url: https://github.com/Tr3V3rn/myweatherapp.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ecr
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: github-oci-auth
  type: oci
  url: oci://683432915883.dkr.ecr.us-east-1.amazonaws.com/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-auth
  namespace: apps
spec:
  encryptedData:
    password: AgAIiofbiOdUH3bq3Ig0aAmhZ0faAQQNR+QF8lYpD3TmbKDICHQzEFVgExGnj6e2CG9IIg/gkbg4QjoFSJ+i+9FNDO/m0jFQRp1osIt9mPQNwuouim3sq8H9AquZ9og7zYFy+wIaF+8+4RLsh2KNlCfAlzoJlEzV0p6MUd6sGbDAL1ZNFgz2l6pEDNogV7HtlWRzP35Dr9CMzmQhtCi1B+ITE5fm181+9UjKiex8ZU9xC89HZTrELOtMf8RFWb/gUaXXB91/+gp1QaZUSDAzT7bZpzgP2tn78iOeyQuUsicaxu4d6oUJ8m724+Ogr69GJFz8Hn4xxjgob6Oajq/6p8+0xB8Yi2CUWhq+IONyqddIDNkMyilFGk8gGLPqtBWknZdRBxpmiMI5eREH9RYUCVtd5KvVpyKjcY0N9QvimZ91LmqVR8D86hMf3S/FueCdZ2CAMoqEjpjhjwVULsmIP2Gim7yoYQYGF7cn9L4BdHNI17zw89bnkUpciXBvc0FIU9I+MXjUaN0+2nnqBu9FB311tsMNAdtL/nSms/x5AG+dizu8OcHZVm5g+I8e7bQFmaby3q8A3mmbxQnCw01u0Q+AV9m/4CGyWJSMcmrCPdwp6P/OEpfBeR6oq1AhXCBfm5rHNuxBxl4wRfDlJdHUAYZxSN7NrXkCGLzAGCqYHDLS2Cq3gukQQW+P23uRSauEsVImBlghyLH20/lldz+AsPJ9DsXO7d6bRiK0zAtA024+BwEb3HWO95mF
    username: AgC4pdwdF/nx9H9TFIG1zPHnECk2IZkbjwyrX/YaftFmuAROg97AxZqSBkk3B1ShDdtZRd4scpO+z+drRxciGPlEMP+sw630JXX0PrssV+hVURIhN73/mLzIyKPIllox6Etg9MuYryk402uLKNpq+jfvh5KAxXg1WdO1xbVE+3TuFzPNjCEW8BTXzw/45fSbK5zUC8wt3rIRDmZHuHvFlS4+FsiVGslbOVrzospPCX6NVoQBTUt6cIan6schyAzWkZi7FENHj3JGiGAoWGrDvuoWzQyuQcrKnvRm1/y/Zf/Y9Ven7wl/pUwt7u2dc6FdLmzvXs4Xo5hiJP2JB6dSCmvgGC3WxGs+uvTtm+9onnFetRHV9MCnyJzqPy8XJ3f16Hu0l8t2D19c1cXG2LjtU5kCureIsm63Oi+2ccKl69GRisVBWE+tdfOmZaRAUoBQvPrcsGKlPgNPYLZITDRuipKzKkWHiNlgBmaBRDN/Jq7xlXR6UsdKh1tOvcGeeqv22gKhFdxcPFK/vLu6XCCgBiEjgRZEHKr/6AtThHIJTtp1KwH8XT2ql65cW1ccYCg0FO3fXokIfyI2eSOY2CJtiyN2YuWTO0yXcuMaV1OQ4CpiBkJNHRZiJMf1kK3T9sHnil85B0+7kAsZ27vrjcKPVTkxWHyZTy+lf+SlL0HdQmt6jsfNXgxmbnYKJHphOd3qvblQ6S8gsDph
  template:
    metadata:
      name: github-auth
      namespace: apps
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oci-auth
  namespace: apps
spec:
  encryptedData:
    password: AgCysV9sbHa77d3uAuIADrH8fNuUnyR/9UVAl2I7SBx6I4OOA0GQ2gEfXG6lV1PNu5vkoekHV8QoTuPFSdRZE0bUA3dgSpBWiZoerDpFoXgBsRxTN61kGKTu+IOQ+tCNa/8OW9XZyaXy9AiPP5m3NPWBOheMEawDFjbyc6bUd066is3VZkKZUdwWB+Zl08YIo01Ju50RcSYUXwpLSNDqJotlbL3iepkUCtltV+nsOPJJP/9eOMZLUE6ASIJwGZl1khDP+vQsZxBx2SiCMN8FJTLtArmBrRGSSfvllJ/OzojqO16nS7po6jGqGsBDAySn6rVybxpZ0IzWPtc/kw4QyTepaKsGJ6x6axzF/f2lB6DYfw+/KnDzZtqGMRg+TeUJv/tkRKV9wuhSAKIFhZF+j2rUR2bbGBUUIzgCYMvDFNLWqZ+joItNRO0vcxIl/IAGDvRE/RqGwnkW+BNOlOU3Dn8NqHL3x//HVvtx4TQFnkeWL92DG7cmIyQb9MifQUgwSmwKGZDMhuqh3eTKYo+bpktKzH0IlpbYqm44QbXRIq0wCpeyX9Ftce4OKg61Q7smy4OAqATrZ9yA14WW6h9XXShN7TsvKcN6FIaleaapPtO6C1+S4Q/xEHbVzOCgnzJqOAQ9ydH72ZMOP8biLaiOKaNCnmbqLEAaVw/CuH/Fhp6P6e5KSX0gM5yZ76gkGdAfpMtU4ukvXobmjewzmRz/GeBj4wwdiEbXk0zVFyncEhjxpesGuCWDsSBwzpknKwVvosRxb9VtqKkr1jD4uopEzgxkUxjU7nIdUv2xZEdAIuTuUYkvYNPkO7rMDzAnxDMeGSLJbvTujHqMvLzq+iUEZU32rslyKVu1We5W9wKrRf7B4LTZfpCatwg64/71A9kEGFIBz50Jh44fM4dfmmJpeUJr1nTPgK8da+Z2zCpqjbQg0lPaNFZHppExaYfLxb8gV5zNNjZM5QnFWXmxdku07sPw3ADM6nrpD1SftxWd7u0pHeQD5Wspf1Aw1yPQeNeXc6SDS3oyHoXYGB183T1ibbld0qZeETYFet8g8pQO0P2SRSvqeKwuCsi8MGia0aj2p2G/KqNJQpv7USq9ODsDHy9Q50AUqnxhXnfCxXKkpgmy+OS2ErPZx0ZbeHjNvfqnqmviLXAWTqFEe5xkmfAKY5yyFJE2ZZnyLugEHFuuxOSTodkDhT94mvj6aW56s8CgxeQ1zjAaSEr+5YhUP5WshDkpzV035azoTN7XRgnI7Lyb3/VKeBPoILRquCLD3aAJZxiAD3AiPIYG0fUbr3W9pN6+dlAT4QO12nxGvBKLeEsCSRqDZ/4g94NomLltXFYrZ62VOBdqHjVun/O3dUdPYBRfWWCp/TSz9qrd7Chu+WmQWyU4DJss/LwMn3Wfgt6XqfIBzPITxf74xMOt1yXY3R8tbPhEkgYYkdSOkowETZJFsmdXuEQa7LjzjKdNwE9j3ReGj97kLPr3Lzyei73BHGIDb3Pd8Tx2+S9dsvmfQW2isUS8zIaIrud01de6vGb5Xrb0dSPO3pQ5lToftJEHV4d0Ffo0kF1rpJHzEDe9s8h3hX4GNipiJobAqUbtU2CcqLSPdViDM1QnM2qB1n6qW2eKp0fvCB1xQz7QMnY8OjWrpJagxsXg2WmR8dwOEXqjN8cfA8RFTCnBBX9+5UU7UKzzqtijsVKDup7vjZJ1BkkgsJ6rVoS9Wjk2IyA2llTrXme4ZFOyf9D0A2tYJx5u9niMDZCBvOzxAhhMpnfKV/a5UatyvK3FLqyWAxehzGcBnbzjhFWNne7OmCfh0I7IrkD8+A+auFRvwLOH4m6zlO6KARn3xEqcH7vNZ8wz3wp8Hdb0gheOVlYRMpRtHQnQUCPnPQzTL8fvJLQBRUFG4aQY69qv2aZwIpwA6hp7fPvcBRVIRWAFJ6RdfTmtvuuYi8GIUBj9voW4xd9dySLpEiyAEt/k4urTwLAdg+vQD5bBQlxEcTvXaMQj9lOeBH0xBHTm8XcVuA1DSg7AuYRBlMlZKdmYu74f+jHCNnvW8B/DS3z/QPRsZX6T7MFOoDpYCFcCYVROcf70kFELfSQv361ZICzMDnIOuW1FPp6trOQ+aJeJTrOYV89SvFvbij60k5kh4aNtsRY+MKKNr33dkKrJPbrHSuAQugS4y4CCYQHshxfxzxPyO2AGCo1KbY2L4yop7PXEP24/7JE7Zio5fgVSpL+xvoMnbAk/8wllaNBsnOqAgnI49BOXOTe8PJqV/M3NmOsrXKuW5iTKJaIUF4QUjHtGwJIdXh0ypZskFpUBh+Cfu3hTIwT+Cl0TgAsLh49Il3iH39HSv4k1ziGZL8iJxIeLH2S926g+mFFy+OO4EcivYdUCTMaSgio7chEYFfaOZcUT/8XFpRfZqFaruOqxwnLJDV/+DiE9Cd2PovXI3lDzGoJP6LoMNLPnphiINnXRiBNttNXKVnVgJVNnWfnA
    username: AgCtpqKjHM6vm3zt8E9ZERLJnBOzRcTgXvQymTqdE5mL5qhNTv6wTu/OR5ecpAi/eKcfyR3qx3t/OoXvgAidJDdQFVoD8u0r2EtyfMCnPzq9kEjKgGqO3j73dvvypTqpfoAUAj3dGQEKQXCg1ZPMDkPldErkWCqW+PrGxns8xJ5gxPI1regXxiVRo53l5mL6viMuinKG1ea0ghWpAh8cRYcxIqgkW9RPDMXMOgI/HieUjdtDUCFFTiPRXH3Qqm849MvpiGgM4jzPmv/gxh1Cv4gVS3duI1RDRE3wagiar23xqbZrzilc8oj0kW58wAYvztcAwjjaSbCX+mfiNaXciDObLMyhkRglh9n0uv87NUgz7GekDchr4n0C0aU8K9XKrNG1aGKRzfOAbjVTy7yH2cDZyXIvrAjY24BNJscfY4BXyzq435Hs5OvFESIB+BQiSxr4lkmwpYGEpWrq/1wnd3oKNyPflpgU5KwzhbypqhVI/NStP0/6uL91QfZl8fvai2VA5b2ZKHRxGk6JAF2MNdIijsA4w7ROIBolTf9ivdbfnwWJqBHKxBeKHj1QTngcoPyxxD1rA2Uk6AbAtdugW4RgIeC+tY+s/0bSplJ6bNpho3vHbGM+I6bkz6yq3xOALLXcYd/o/v4W0kjGHzwIvYrMfBQ7QCqm0wdq1Oaz6dzJpPuMGKWRNIj7l1MUfMGwrXiTzU0=
  template:
    metadata:
      name: github-oci-auth
      namespace: apps
    type: Opaque

