---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: github-auth
  url: https://github.com/Tr3V3rn/myweatherapp.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ecr
  namespace: apps
spec:
  interval: 1m0s
  secretRef:
    name: github-oci-auth
  type: oci
  url: oci://683432915883.dkr.ecr.us-east-1.amazonaws.com/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev
  sourceRef:
    kind: GitRepository
    name: dev
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-auth
  namespace: apps
spec:
  encryptedData:
    password: AgBmArlhn0ej27AEf407UaJZSJFRxUMXkBVBkxszJP1re+iV3F2YXYdHdY46f+5fthGwtSI1QoDBkcIhzOM8GWnA6Auayts05GIzcLsfjLD0UOZmn/EEYoP8EYyUTrYPRkIDixLzIR8eqbZNUTWFQkgNp70Oj0b9ANdd4XrqZIbCjiGjlPgn/a8keE4buBH1juPp6UVVh4vDWRfAV54nGHzlsXFKavH4R2haw/JOqMcm1Jv1hveL8kqbkFBFwG1+OaWF00LnMufW5EfYuSzxIHJaTEjeLnmAwkzlzN8lNft8MG+m7KXUUQkFbeFlZo+7ZRjX0134ubv8ohclKeOObMZbF9LMEERK7zKa84x1MTzT2gzQRVAJ8MX738XNMHNkpNXrXsqlvsu8r0hntAI4FXpvmhOMs7w2drgrRybPjeJ+E4d7YKimmysNBEzyokx35ntOeBWOOwhri3NKGPzMUi4+JZ6C4nCEBsN688hbYl12ITjidgcm/VM3oTCf/C9nVZUeE+vidEuSkZqPLQwIzaRGQc6N8mgfvS8HrgyMNmLamjWDBrJ3dCAsxRgKnIkwrAcs9N6liUBXd/Q2z31iSFeDd41axiHoMb+RJlCeo3ZxBor2TkG5772dJTCmy40jU+kr28lLwK7Un6wxflKDoYEB6FveyaVGYR2LMYyRRPN8xBkcMm8qEvCozfR7dQDo5Aet/TRyxiLRI9BxxGALfQlmTYnrs/KvQKL9QfNKpRy/cEghzQBJj0+2
    username: AgBaLZJRWZUMFyZMXqyON2dBZEpckauoHPC0NsYrHouMBhjVGGQgTNHfJ5zgj8vW0SA7ZmrYbUCIMf0FKbSHIheAzjgBL/tH0mtMi3KmiiTgTmmcHkCNMo8n2GAtMeobqbuYb6XGFacVXLY/025SRN0peBsH3LuqZehjLbEnAERayqkUKqIv69IjsAibPyJtI8AMdR0uWM1PU/BYLGA614+vJlr2QVWYZjnf0XpBxfeoIPGvTEFEpQx5GAR+VYEbzgZEZlJNEqIUw+k9A1zaOVJ+YmTwoE8Lze5Bh91H2e9ITDTQ7ieBwTDYO0ClX+NoLyOEBJJMfdXz+j8CZpyhpgGRamRFaRivcIITyArySKtKakSqTfGM7XYHTYkcHAU9/2nnUZSWaEqrnUvK9q3HsUo1MLjQ+lnUvoCUI1MUQZFxWvaxWRjdIxC+A1V1kLT6u63Y//M/9XEcMKau0p01mDpsaKcl9jxRcdsCPp3xA2ust/GZYsEZuBTSRsJb+bKmSIMCAekr9DnVmGPcotyjyJZ1/bT6/0oNWhElHd+4F04l2BMWnXFvgFs+R1KiuOsNtPqKuonDsp3/IkyZG2t+7mS9bhpQ9DWnuWkqe57TfKJMtGxGd0cu9k9JTuPRJ6KzLku3SFaB7B2nL+D8BGd4e+J2ldmqyJDiD/9RsH1R4OIXvDQnxYW/imiPokKl29lDZXADm/lFf1km
  template:
    metadata:
      name: github-auth
      namespace: apps
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-oci-auth
  namespace: apps
spec:
  encryptedData:
    password: AgAOoxHvL7SF8Vn2AYruVh6dYnBCJRq7ZgDmbLLEgfvKDkaNrGqfmYF0LK+wyTSINFH8ImobTHHX9D89sexRqG8oAWLuvKwqSMy3qLwBW0A/yOE3B3nHAqRyaM62QNPaHSu2fbdAg0BzB/Nb8LgS9ME1lJAy2I3w3muxLULJz/3qRL5q8kEw035N31CR4cSM5lWUz+iVZ9iZcnVshFjyIBtuQky+re6GW2PyJ49vGpJWXEzDfQWOHabEsDo2DhCxLjhaUd84T+IKkD6GQQHCx0KI6bQt4+VerubpRcLgC0DFMTE0+IpcsGFBIk/Tcd8g3uhigvRfiAHzzLL/jp0UTMXr2ZRWGmKaJihs/35TxrBT/ooka+0ak9byX7u6foKx2myPrn/enqD8H54EBr+xFP9SHCa0vcBJr/wsKhmmxwr/pL5sHRcejphHahD8pJeZpxpTT/UciSfIuUGV0JgWWFd/S4H6qoZ1e0BBXarojilVmmM0Lwz/8ceMnlfdn3tkHm6cwfXan6XjQg/PGEQDEMcYzlFbwgZLz5bBKSt8S7PuIhFFyx8toAHuWkaREOsVbvQJelmf+jW72EqjaSi9Jxr2fEZdXIjF2yRAcR5pnq6TFGJKd88o+KZiGVsCeTfSlwIcHD7UgRxbZkAotgKVgGv/o4mxODx3ANAeAN8YuY45L4MLuRtPfXEu9CBHn1a5VnDBLkefi8ibJQWZVd7Fwxycp79BW9Ptn82p8QGwc3ib7+aa+bKMTmsmDZkeb5BLGXs85weDGpgbGTOin6UqbOSa0se81ExSEDXVc02Q7ryGqXxOiYI0sYaT7uDwOXzZ65+bl9oxm9NOafja8kDh7wqWMIS5s7vSDP7/TebclihKAxOTEAh3xPyF9c/CyBk3MwV5SSVNIWWPxph30ch5FG0zg09v8QFS35tz7N9KLVuNuwmPfge1MzuqfSLYcBxeBgg4xuLyW4eBUSPeYOaNv7J9NtlqGx18IsfVw8J3VIde609r6kuKMT66pXO7jFuW5lzdgFlnVaDXooifSARISG9ZvBvM0fGH8oqCqxhYVfii+rsAl6ltQi1cBtX2P/ykFPCTJ2zFaP4zP3jwnQlR1WY5Ue9AUG3FdnGqQLOq9N5Vz+QfWR5lIR6q6j6sCpJPqMho9kHXirgA+JXAlCnU5B4f9YKiuq5E7Ih8kiqTceS8ZlZmaaL/Lg7poKjrEh6r+Jzm8ic9xwOvXkySAMHVtVIGBFQcNQZPS3Wtsp/PDKLkUOMMzfyQBIFj0Z8aQQJlZ6aW5Unrr7G6cml0SB8m6ZhPwF43zommrsFfH57qMA97gCufsPHrfrmHaGrLyD9mczf2acz8RwoRgMn7KPylJ0i+Dh76xayrY7myodO1Kp0igCDAfJ5nPLVf1DQWzmk95dY3HxK08+GdhRnsH6TjqEMacXoElNVXgDmR4kykOLLi7Vt/kqkvMtAnHlol/c567M3Rk4IQ7kSPLRCZUiDnypYxHmrHa4LvlWjUdcsWVdYJwn4gTE7x6JzKfr8yBYOeJfS2DiR5HBHDG8PwEuSF7y2c2x3APqZejkMON37HKwuvdYzm/Rr2ZpMvjqnddv33mlV8/vc49Is4lMWuKEsl4i8kuoCmhcYdv3ZjwTpV4n1aJ6YZa0unyO0WSdT43xqmI40JBJYYuVuzJV/VN9AI5OBHScPu+boiO1erH/RyYcU3Pg/YI8UaDpG8udvxjpdA4dXRFLlY16F9Kye16Dlobu9B+X4/pJXgBGeBWUNHhmqfcM9bc3h1Tj4rJOmYUpXW8Tw4atIESRgrjd1CDR3roTrGAeZmR8YiFLdUI2A5MJFGGCcQ8uk74xpcR1MB8HpJ8mmX7u+IpBQh+O1CRQMaKMTwokcspITYflWhnGvQ77aevqYoArRacCXfJOammJq1dDUgP3bMREyV+mO1rSuOz8l/ohIubvHV4YKy1k/g8c+Au0nv45uEL+5hZDFglR7Jknl/nXhMQ0M1ZPg44k9ZNrpIPtw5FkUS3+UcKXvWb4ADNK7mTHvbOuT85QFmekpmvOQqA6aS1JW9I3F7hvkg9s4JG1gTFnAbscdNgRih07Pu/ffEdyFLYM3JsrjyuZa26BClyM+2144PYLd53VS2Ofxd3zZxjEKijkRVw5PELmTV7YtIhuoGLsMB5URUIemB3pFeKagLK/az72woA8BmqKGuRVgd1myxpOj7gKYfUDSRX4Da3l9almJJZ0UPdgKH87OzbZv6a9FiFFpqTxN3h1lFtj+GP0FEGwppYybzILVMwu9dZhWVpNGG1gfJSe8A/ygVmaVs2NQ8AvoLMpUoJ1R64mzGV0o/8T9pdu9h+j2+PixdV55V/pTJOuwGCCTkdiBCJTcfnfQrNEgx6Y78xvK8QP4/LyqV61nushdcrnaqiFmxFiUbWZdQNj5ooBOq1JNo/286+IIj5ZbGlZXa9AgeAbBZfG9CD27TvJ9apQysdYK11cMZs1F3Et3DV0vfwwLvnukZ5kQos7Bwt3jb3zNiymlYt0IF9+2VihB5uMP7rKAsF2I09xPePA4+VnZaN3/B3zBIC+9uWAa215yg4xGzn3HdkPHq7+ebdTz08MS5qMRBmTZM8AzbFXc6qvpK9cgXtLkkqlcXRVgoaxfaMUt4s2MUyb1htGgrrvjW4QAW2Xj2LRfMxRm0VK0+zd0fErBTrgRKuUoP1BNTWSCtEjti9aJjMZkKd/TG2kGP7WG1/xAKWtXjsMZV7QZ8sWZTw8fjpH8Tw0VgTKASsBfmHGoUigNmj5JmYxDMN0+pnjD8trWwBcUSorBhT9saE0IRQsO6kRizmOIagJ5kXDP2cdU6UwzC7zRevSia6mV6tmTDcELCCsALQATbEJzo1FR7piKUWB4LeTp8WLBK5GqNmoF6A+FxF6O6vBTsUShunjvSxanu0I8Q9GFEh87BmpVEUNMlRSsY9WP36/qlUpA7hBebgoT5fR59KRIys/X+8SGns1CtdrN31NnHBZKd2i2VP6xFLR9rEE42JJdcJX5h7VMG3DRHV99tO2MgyJaCiVPhF+IrqKGFF2hHF1fbIWuJcMkFMeI8zh8GjCDW8GNzj8zX
    username: AgAtCsn8gLdZIS05cZ3i7MdFeMTSnoHenB/R+NvjlNRWkHvlK9NfcygxxTNRlpzqk2uOmZB6N7ImAdqje56rKXUxPm+gur22xjiaoInnoYgIfD3+BZI6uiMMmHRf5AhbAdmayw7kstWUX1iEhtAmEtAM8CjciwIaaVGkMOxI9UKeEYuNb2vXXI+v5dwYPtWlwOj7XOxNs7IH9VM6UBBGHyXkeClt1s9DpsQ7eTkBW7bKuLGlEqSemO2+6Az6PhC09wXRnW0ggCDyXqQ/7A5bZEg9yco8OlL2nx/nvy1NIaCyfKbSezvWnItt3E7Q0OvfOv+UviFYKgylsVAzfGZx/M1K6er1mTWn/4S+dGlhJqRV08qFUu4ySPCPvK97dHv2BsoRPfhKh2FeF7LRs0do2k46qpmlgdjo1ehCAWxxvvbHZYAvxPbvdQJ+XOzgXXAErxNWQY9L5V/pX1jmK6wur55TIDHNQb8v/h8AGykR/Vr947kH4LG2I+9D93rx/VFS5GXusQDNWtDlED+P4mUNvNmLEsOhtTalTKdPVWstKnra6XqyrojXu9SYzc0qL5Bdy7kfbgFqMT4PLP7tzSER/m1cAHu1GEGHvjcTwFS8G9MCishx1d/aExx+PC+3LKY0QIMqlyAmRpKL9RXCqmoW8W9Hvg8YSgSXpUHy0a1p06NQJ9YJy7bkZG18Xz2FlWWf0bxyz+8=
  template:
    metadata:
      name: github-oci-auth
      namespace: apps
    type: Opaque