apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 5m
  path: ./tenants/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true