apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 5m
  path: ./infrastructure/controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  timeout: 5m0s
  patches:
    - patch: |
        - op: replace
          path: /spec/values/ingress/hosts/0/host
          value: "dashboard.staging"
      target:
        kind: HelmRelease
        name: ww-gitops
